version: '3'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: payroll
      POSTGRES_PASSWORD: apasswordthatnobodywilleverremember
    ports:
      - 6000:5432
    volumes:
    - payregister:/var/lib/postgresql/data
  registerapp:
    build: .
    image: process-payroll
    ports:
      - 8080:8080/tcp

volumes:
  payregister:
    external: false

#docker run --name db -e POSTGRES_DB=registration -e POSTGRES_USER=payroll -e POSTGRES_PASSWORD=apasswordthatnobodywilleverremember -d -p 6000:5432 postgres:11
