version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: payroll
      POSTGRES_PASSWORD: apasswordthatnobodywilleverremember
    ports:
      - 6000:5432/tcp
    volumes:
      - payregister:/var/lib/postgresql/data
  registerapp:
    image: neemiasgabriel/process-payroll:latest
    container_name: registerapp
    ports:
      - 8082:8081/tcp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/registration
      SPRING_DATASOURCE_USERNAME: payroll
      SPRING_DATASOURCE_PASSWORD: apasswordthatnobodywilleverremember

volumes:
  payregister:

#docker run --name db -e POSTGRES_DB=registration -e POSTGRES_USER=payroll -e POSTGRES_PASSWORD=apasswordthatnobodywilleverremember -d -p 5432:5432 postgres:11
